// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VRZoneApi.Data;

#nullable disable

namespace VRZoneApi.Migrations
{
    [DbContext(typeof(VRZoneContext))]
    partial class VRZoneContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("VRZoneApi.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Apellido")
                        .HasColumnType("longtext");

                    b.Property<int>("CantidadPersonas")
                        .HasColumnType("int");

                    b.Property<string>("Dni")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Jugadores")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .HasColumnType("longtext");

                    b.HasKey("IdCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("VRZoneApi.Models.Estacion", b =>
                {
                    b.Property<int>("IdEstacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdEstacion"));

                    b.Property<bool>("Activa")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.HasKey("IdEstacion");

                    b.ToTable("Estaciones");

                    b.HasData(
                        new
                        {
                            IdEstacion = 1,
                            Activa = true,
                            Descripcion = "Puesto con visor Oculus Quest 2",
                            Nombre = "Estacion 1"
                        },
                        new
                        {
                            IdEstacion = 2,
                            Activa = true,
                            Descripcion = "Puesto con visor HTC Vive",
                            Nombre = "Estacion 2"
                        });
                });

            modelBuilder.Entity("VRZoneApi.Models.Experiencia", b =>
                {
                    b.Property<int>("IdExperiencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdExperiencia"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("int");

                    b.Property<int>("EdadMinima")
                        .HasColumnType("int");

                    b.Property<string>("Genero")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.HasKey("IdExperiencia");

                    b.ToTable("Experiencias");

                    b.HasData(
                        new
                        {
                            IdExperiencia = 1,
                            Descripcion = "Juego de ritmo con sables de luz",
                            DuracionMinutos = 30,
                            EdadMinima = 7,
                            Genero = "Musical",
                            Nombre = "Beat Saber"
                        },
                        new
                        {
                            IdExperiencia = 2,
                            Descripcion = "Experiencia de terror",
                            DuracionMinutos = 45,
                            EdadMinima = 16,
                            Genero = "Terror",
                            Nombre = "Horror VR"
                        });
                });

            modelBuilder.Entity("VRZoneApi.Models.Pago", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPago"));

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdReserva")
                        .HasColumnType("int");

                    b.Property<string>("Medio")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("IdPago");

                    b.HasIndex("IdReserva");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("VRZoneApi.Models.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdReserva"));

                    b.Property<string>("Estado")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HoraFin")
                        .HasColumnType("longtext");

                    b.Property<string>("HoraInicio")
                        .HasColumnType("longtext");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdEstacion")
                        .HasColumnType("int");

                    b.Property<int>("IdExperiencia")
                        .HasColumnType("int");

                    b.Property<string>("Jugadores")
                        .HasColumnType("longtext");

                    b.HasKey("IdReserva");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdEstacion");

                    b.HasIndex("IdExperiencia");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("VRZoneApi.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Contrasenia")
                        .HasColumnType("longtext");

                    b.Property<string>("NombreUsuario")
                        .HasColumnType("longtext");

                    b.Property<string>("Rol")
                        .HasColumnType("longtext");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            Contrasenia = "admin",
                            NombreUsuario = "admin",
                            Rol = "Administrador"
                        },
                        new
                        {
                            IdUsuario = 2,
                            Contrasenia = "1234",
                            NombreUsuario = "recepcion",
                            Rol = "Recepcionista"
                        });
                });

            modelBuilder.Entity("VRZoneApi.Models.Pago", b =>
                {
                    b.HasOne("VRZoneApi.Models.Reserva", "Reserva")
                        .WithMany()
                        .HasForeignKey("IdReserva")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("VRZoneApi.Models.Reserva", b =>
                {
                    b.HasOne("VRZoneApi.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VRZoneApi.Models.Estacion", "Estacion")
                        .WithMany()
                        .HasForeignKey("IdEstacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VRZoneApi.Models.Experiencia", "Experiencia")
                        .WithMany()
                        .HasForeignKey("IdExperiencia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Estacion");

                    b.Navigation("Experiencia");
                });
#pragma warning restore 612, 618
        }
    }
}
